### ISSUE TITLE
Test helper to wait editor load

### ISSUE THREAD

**Issue by robinvrd** [concordnow/tinymce-ember#183]
This addon does not give any clean way to wait for tinymce loading in a test. In the tests of the addon we can see
```
await waitUntil(() => {
    return tinymce.activeEditor.getContent({ format: 'html' }) === checkValue;
});
```
which is not really clean.

https://api.emberjs.com/ember/3.28/functions/@ember%2Frunloop/begin might be a solution

**Comment by ctjhoa** [comment]
Fix released in 3.0.0
